name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Locate gradlew script
        id: locate-gradlew
        run: |
          echo "Searching for gradlew..."
          GRADLEW_PATH=$(find . -name gradlew -type f | head -n 1)
          echo "Found gradlew at: $GRADLEW_PATH"
          chmod +x "$GRADLEW_PATH"
          echo "GRADLEW_PATH=$GRADLEW_PATH" >> $GITHUB_ENV

      - name: Run ktlint
        run: $GRADLEW_PATH ktlintCheck

      - name: Run Detekt
        #run: $GRADLEW_PATH detekt --config detekt-config.yml
        run: $GRADLEW_PATH detekt


      - name: Run Tests with Coverage
        run: $GRADLEW_PATH testDebugUnitTest jacocoTestReport

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: app/build/reports/jacoco/jacocoTestReport/html

      - name: Upload Detekt Report
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: build/reports/detekt

      - name: Find release APK
        id: find_apk
        run: |
          APK_PATH=$(find . -type f -name "*release*.apk" | head -n 1)
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
          echo "Found APK: $APK_PATH"

      - name: Build Release APK
        run: $GRADLEW_PATH assembleRelease

      - name: Set up Google Service Account credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > $HOME/credentials.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/credentials.json

      - name: Deploy to Firebase
        run: |
          firebase deploy --only hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/credentials.json

