name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create Firebase credentials file
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > "${HOME}/firebase-key.json"
        shell: bash

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.HOME }}/firebase-key.json
